site_name: My-Docs
site_description: 'A Login option for MkDocs Material'
site_author: 'JRichardsz'
repo_url: 'https://github.com/jrichardsz-software-architect-tools/mkdocs-template'
nav:
    - Home: index.md
    - About:
      - about: about/about.md
theme:
  name: 'material'
  language: 'es'
  palette:
    primary: 'Teal'
    accent: 'Indigo'

extra_css:
  - 'assets/css/prism.css'
extra_javascript:
  - assets/js/prism.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/giansalex

markdown_extensions:
  - admonition
  - codehilite:
      css_class: code
      use_pygments: false
      guess_lang: false
  - toc:
      permalink: true
